### ISSUE TITLE
Add property tests for luhn

### ISSUE THREAD

**Issue by yurrriq** [exercism/erlang#100]
Adding this as a reminder to myself to make a PR. I found some interesting edge cases this way.

**Comment by yurrriq** [comment]
One argument against this is that it's awfully revealing. Thoughts @maintainers?

**Comment by NobbZ** [comment]
I'm very keen on prop-testing, but currently we don't rely on anthing not delivered by OTP.

I do think, that introducing `rebar`(`3`) or `erlank.mk` here just to have some prop testing is too much.

Also this change would not only mean to just PR that single exercise, but also adding necessary stuff into documentation of how to install and get it running. I've touched some tracks where documentation and reality is out of sync drastically and I don't want this to happen to erlang (if possible).

**Comment by yurrriq** [comment]
Understandable. Also [the tests I wrote](http://exercism.io/submissions/2e5f1aa84b5f4d5c846a87c5c1947f4b) have a crude reimplementation of the algorithm, which when shown to users, makes it less fun.

**Comment by NobbZ** [comment]
I do think, that property testing will expose at least a partial solution to the problem in general, so even if I am eager to it, I do fear we can't use it.

But since using `rebar3` (#106) is a fact that has been decided upon, I will definitively reconsider property testing about next year.

**Comment by yurrriq** [comment]
Closing since this is stale and too revealing. The property-based tests I wrote are linked in case anyone is curious in the future.
