### ISSUE TITLE
Setup instructions for an erlang environment, ready to follow the exercises

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#121]
In #113 @paulnice revealed that the instructions to setup an erlang environment lack some necessary detail about requirements.

The setup instructions should reviewed and -verified to cover installation of a recent and complete erlang on a fresh installed basesystem where the following basesystems should be considered at least:
- [ ] Ubuntu
- [ ] latest Debian
- [ ] latest CentOS
- [ ] latest Fedora
- [ ] Windows 10 using the installer

**Comment by paulnice** [comment]
May I take some items? First three? All linuxes?

**Comment by NobbZ** [comment]
Even if I'm happy about help I think it would be useless at the current
point of time. I'm over hauling The complete track and as such I will
switch to rebar3 as build and test system. Of course you still can start
and do some experiments using the version of hello world in that PR.

paulnice <notifications@github.com> schrieb am Di., 20. Sep. 2016 18:11:

**Comment by NobbZ** [comment]
@paulnice I have pulled the switch and exercises are using `rebar3` as build system now.

So if you are still interested, I'd be happy to hear from you!
