### ISSUE TITLE
Add stub solutions for all exercises

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#145]
There should be a stub solution for every exercise, roughly like the following:

```erl
-module($module_name).

-export([fun_a/0, fun_b/2]).

fun_a() -> undefined.

fun_b(Param1, Param2) -> undefined.

test_version -> 1. % or whatever version is needed to pass the tests
```

Also we need a check in [`bin/journey-test`](https://github.com/exercism/xerlang/blob/master/bin/journey-test.sh) that fails if it is missing. 

```bash
if [[ ! -f "${exercism_exercises_dir}/erlang/${exercise}/src/${module}.erl ]]; then exit 1; fi
```

Should be a sufficient test, best put between current lines 201 (introduction of `$module`) and 202 (overwriting any stub that might exist with the example solution).

**Comment by JordanAdams** [comment]
I've put a PR to resolve this here: https://github.com/exercism/erlang/pull/177
