### ISSUE TITLE
Recommend a linter for erlang?

### ISSUE THREAD

**Issue by kytrinyx** [exercism/erlang#16]
This may or may not be appropriate in this language. See exercism/docs#54 for details.

**Comment by NobbZ** [comment]
I did only find a small handfull of projects which seems to use elvis, one of them has been from the elvis creator himself, as well as elvis is beeing elvis-checked ;)

Also there seem to be 2 community styleguides available: 

* https://github.com/nuex/erlang-style-guide
* https://github.com/inaka/erlang_guidelines

I did neither "diff" them right now, nor did I do a search for implementation examples of them, as well as I did not look out for software enforcing them (while knowing that inaka is the maintainer of elvis)

**Comment by NobbZ** [comment]
I will close this as discussion staled.

Also as I read a lot of erlang code these days, I realized that there is not much consense of a styleguide, so one has to adhere a different style in each project one participates.
