### ISSUE TITLE
raindrops: Implement exercise

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#186]
Implement the `raindrops` exercise.

> Convert a number to a string, the contents of which depend on the number's factors.

* [Description](https://github.com/exercism/problem-specifications/blob/master/exercises/raindrops/description.md)
* [Test Data](https://github.com/exercism/problem-specifications/blob/master/exercises/raindrops/canonical-data.json)

**Comment by AtelesPaniscus** [comment]
Implement submitted.  See pull request #229.
