### ISSUE TITLE
sieve: implement exercise

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#188]
Implement the `sieve` exercise

> Use the Sieve of Eratosthenes to find all the primes from 2 up to a given number.

* [Description](https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/description.md)
* [Test Data](https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/canonical-data.json)

**Comment by AtelesPaniscus** [comment]
See pull request #201.  I hope it meets your requirements.

**Comment by NobbZ** [comment]
Closed by #201
