### ISSUE TITLE
bracket push: implement exercise

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#190]
> Make sure the brackets and braces all match.

* [Description](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/description.md)
* [Test Data](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/canonical-data.json)

**Comment by juhlig** [comment]
This exercise has been implemented: #241, so this issue can be closed.
