### ISSUE TITLE
Raindrops tests are not very informative

### ISSUE THREAD

**Issue by vassilevsky** [exercism/erlang#242]
Hello :)

Thank you for your work on Erlang track!

I just started it and got to the **Raindrops** exercise. This is the first exercise with such tests:

```erlang
sound_of_52_is_52_test() ->
    ?assert( raindrops:convert(52) =:= "52").
```

https://github.com/exercism/erlang/blob/master/exercises/raindrops/test/raindrops_tests.erl

The problem with such tests for me is that they don't suggest what is wrong with my code.

```
        raindrops_tests: sound_of_52_is_52_test...*failed*
in function raindrops_tests:'-sound_of_52_is_52_test/0-fun-0-'/0 (/Users/vassilevsky/Dropbox/exercism/erlang/raindrops/_build/test/lib/raindrops/test/raindrops_tests.erl, line 43)
**error:{assert,[{module,raindrops_tests},
         {line,43},
         {expression,"raindrops : convert ( 52 ) =:= \"52\""},
         {expected,true},
         {value,false}]}
  output:<<"">>
```

I can understand that my function returned **not "52"**. But what did it return? That I don't know and therefore have trouble understanding what is wrong with it.

I think that it would be better to use `?assertEqual` like in all previous tests.

I will happily send a PR but I'm not sure what is the correct way to solve this. There's this comment in the tests:

```
% test cases adapted from `x-common//canonical-data.json` @ version: 1.0.0
```

It looks like there is a template somewhere, from which the tests are auto-generated, but I have failed to locate it :)

**Comment by NobbZ** [comment]
No, the raindrop tests are still manually written, and yes, I think an `?assertMatch` were more appropriate.

Please feel free to submit a PR.

**Comment by vassilevsky** [comment]
Please see #243 :)
