### ISSUE TITLE
Underscore variables in module skeletons

### ISSUE THREAD

**Issue by juhlig** [exercism/erlang#277]
I have mentored a few exercises on the Erlang track.

Often, students new to the language use the variables in the skeleton as they are, prefixed with underscores. I thus explain again and again what these do, why they should be removed, why they are there in the first place, etc.

Now I know they have to be there since the tests treat warnings as errors, and `_test/check-exercises.escript` will thus fail. Also, as a side effect, the students learn something they apparently didn't know yet. But it is somewhat tiring for the mentors (or, at least, for me).

**Comment by NobbZ** [comment]
I've started playing around with a compile time hook and it seems to work in general, I have some more work to do though to make it robust enough for students code ;)
