### ISSUE TITLE
bracket-push: renamed to matching-brackets

### ISSUE THREAD

**Issue by petertseng** [exercism/erlang#385]
In https://github.com/exercism/problem-specifications/pull/1501, bracket-push was renamed to matching-brackets in problem-specifications, therefore it is recommended that this track (which has the bracket-push exercise) also renames it.

The reasons for this recommendation:

* to name the exercise by its story, not by what it potentially teaches
* to avoid unnecessarily biasing the solution space

If this track decides to follow this recommendation, here are some things that may need a change:

* config.json (change the `slug` of the exercise; no need to change its `uuid`)
* name of the directory
* README (contains the name of the exercise)
* code

If you're not sure what needs to change, feel free to examine PRs to other tracks by looking at any PRs linked to https://github.com/exercism/problem-specifications/pull/1501.

When the rename is complete, the person who did the rename should close this issue; you don't need to ask for confirmation from the person who filed this issue (the person who filed this issue might not check back regularly).

If this track instead decides that accepting this recommendation is a bad idea for the track, then this issue should be closed upon making that decision, and none of the above steps should be taken.

---

Checklist (added by @NobbZ)

- [ ] Wait for `0.1.0` release of the tests-generator (https://github.com/exercism/erlang-tests-generator)
- [ ] `git cp` `bracket-push` to `matching-brackets`
- [ ] `git mv` and edit `*.app.src` file
- [ ] `git rm` old test and stub.

**Comment by NobbZ** [comment]
Yes, following the rename is a good thing. I'll prepare a checklist later today.

**Comment by NobbZ** [comment]
I took a closer look, and as `bracket-push` is generated by the testgen, I need to tackle this one as when I do the next canonical data update.
