### ISSUE TITLE
Create separate github project for the testgenerator

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#403]
Currently, PRs and issues that only affect the code of the code generator and not necessarily would mean updating the generated tests are spread and interleaved with issues that do only affect the actual exercises.

Also the testgenerator is the second largest folder in a clean checkout, not to speak about additional downloadsizes due to its history.

Even though we can not change that its current history is part of master, we can surely avoid that it will outgrow the history of actual exercise changes.

Last but not least, when changing the generators, we always have to make sure, that we also commit the resulting changes to the actual tests to keep code base in sync.

By decoupling the generator and the exercises into separate repositories, some of these problems can be easily tackled.

See also exercism/csharp#1298.

----

Checklist

- [x] Create another repository, perhaps `exercism/erlang-generator` (@iHiD or @kytrinyx).
- [x] Move testgenerators code base into new repository, optionally preserving its current history
- [x] Move testgenerator related issues to the other repository
- [x] Move testgenerator related PRs to the other repository
- [x] create submodule for prob-spec in new repository
- [x] remove canonical data from this repository
- [x] remove testgen compilation from travis
- [x] remove testgen code from this repository

Unless stated otherwise, I think the tasks can be done by me.

**Comment by iHiD** [comment]
@NobbZ You now have write access to https://github.com/exercism/erlang-tests-generator

**Comment by NobbZ** [comment]
Thanks!

I should be able to do the remaining points throughout the weekend.
