### ISSUE TITLE
Remove travis

### ISSUE THREAD

**Issue by NobbZ** [exercism/erlang#408]
@kytrinyx after we have GitHub Actions available on the organisation and it will be publicly available in November, I'm in a process of removing travis-ci from the erlang track and associated repositories and replacing it with equivalent work flows.

I now have added a stub `.travis-ci.yml` which does nothing but printing a message.

Could you disable travis-ci completely or do we want to keep it, in case we need it again?

**Comment by kytrinyx** [comment]
I can disable it completely, thanks!
