### ISSUE TITLE
collatz-conjecture

### ISSUE THREAD

**Issue by guygastineau** [exercism/erlang#409]
I realized when doing this exercise with my mentor that the tests should probably expect a straight error instead of an error tuple.

I would like to update the generator for `collatz-conjecture` to do that, but I can even figure out where/what the generator implementation is for this track.

**Comment by NobbZ** [comment]
Yeah, I think raising or returning `badarg` is in fact the best here.

You can find the generator at https://github.com/exercism/erlang-tests-generator.

**Comment by guygastineau** [comment]
Thank you. I will get to it 😁

**Comment by NobbZ** [comment]
Hello @guygastineau! Are you still up to this? I'll flag this as `hacktoberfest` for now and also open an accompanying issue at the [exercism/erlang-tests-generator][1] repository.

[1]: https://github.com/exercism/erlang-tests-generator

**Comment by guygastineau** [comment]
Ah, yeah, I have gotten myself into a lot of commitments for multiple tracks at the moment.

I am more than happy to relinquish control of this work :smile:

Sorry I forgot about this :sweat_smile: 

Side Note: I finally finished the core Erlang Track, and I want to thank you all for putting together a great track! :heart_eyes:

**Comment by NobbZ** [comment]
Okay, exercism/erlang-tests-generator#21 it is!

And I really know about the problem of committing one to to many tracks at once… I that all the time…
