### ISSUE TITLE
Recruiting additional maintainers for Erlang

### ISSUE THREAD

**Issue by kytrinyx** [exercism/erlang#427]
We're about to start a big push towards version 3 (v3) of Exercism. This is going to be a really exciting step forward for Exercism, with in-browser coding, new Concept Exercises with automated feedback, improved mentoring and much more.

This to be a big community effort, with the work spread out among hundreds of volunteers across Exercism. One key thing is going to be each track having enough maintainers who have the time to manage that community effort. We are therefore putting out a call for new maintainers to bolster our numbers. We're hoping that our existing maintainers will be able to act as mentors to the newer maintainers we add, and take on a parental role in the tracks.

If you are an existing maintainer, could you please reply to this letting us know that you think you'll have time (2-3hrs/week) to help with this over the next 6 months. If you won't have that time, but still want to be a maintainer and just help where you can instead, please tell us that too. If you have come to the end of the road as a maintainer, then we totally understand that and appreciate all your effort, so just let us know.

For anyone new who's interested in becoming a maintainer, thanks for your interest! Being an Exercism maintainer is also a great opportunity to work with some other smart people, learn more about your language of choice, and gain useful skills and experience that are useful for growing your career in the technical leadership direction. Please write a comment below introducing yourself along with your Exercism handle, and telling us why you're interested in becoming a maintainer, and any relevant experience. We will then evaluate every application and contact you using your exercism email address once we have finished the evaluation process.

Thank you!

See also https://github.com/exercism/exercism/issues/5161

**Comment by NobbZ** [comment]
I'm currently a/the maintainer of the erlang track, and I'm pretty confident that I'll be able to spend those 30 minutes a day. Though I have to be honest, I can't stem this alone and will need some help, some one not only to ruber duck/discuss over design of the track and tooling, but also someone who then helps implementing stuff.

So I'm looking forward for other people joining the team!

**Comment by sshine** [comment]
I would like to volunteer as rubber duck and reviewer. I can be tempted into helping with the design of exercises, and I can implement some of these as well, but I'd like to characterise my participation on the track as "part-time". I will submit a request to become 'contributing maintainer' shortly.

**Comment by NobbZ** [comment]
I appreciate your help!

**Comment by gwaerondor** [comment]
I can also help out. I've been looking at the Erlang track's tickets to see if there's a good place to start for a while anyway, so now seems like a good time.

**Comment by iHiD** [comment]
@gwaerondor Great news. We'll follow up with an email!

**Comment by bgottlob** [comment]
I would like to help out as well. I should be able to commit 2-3 hours most weeks, but some weeks may busier than others. I will keep an eye on the issue tracker and start helping with implementation.
