### ISSUE TITLE
The `accumulate` problem uses inaccurate terminology

### ISSUE THREAD

**Issue by hjiang** [exercism/erlang#556]
The [`accumulate` problem](exercises/practice/accumulate/.docs/instructions.md) asks for a function of type:
```
(fun((A) -> B), list(A)) -> list(B)
```
In most languages `accumulate` has the type:
```
(fun((A, B) -> A), A, list(B)) -> A
```
Perhaps calling it `map` would be more appropriate?

**Comment by NobbZ** [comment]
The name of the function is taken from the canonical data, and it has been point of discussion there a couple of times in public and private discussion channels.

Yes, `accumulate` is just `map`.
