### ISSUE TITLE
Add Reverse String?

### ISSUE THREAD

**Issue by BNAndras** [exercism/erlang#559]
This week, Exercism is featuring Reverse String as part of the year-long #48in24 event. According to https://exercism.org/challenges/48in24/implementation_status, Erlang hasn't ported this exercise. Since Elixir already decided to mark this exercise as foregone on their track, does the Erlang team want this exercise ported? If you do, I can take care of that.

**Comment by NobbZ** [comment]
As the elixir string works different from the erlang string, I'd not follow Elixir here, though at the same time, I currently do not have the time to add the exercise bymyself. I appreciate PRs though.

**Comment by BNAndras** [comment]
Alright, I'll take a look this weekend.
